In [1]:
import pandas as pd

cars_df = pd.read_csv("data/cars_data_set.csv")
display(cars_df.head())

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [2]:
cars_df.columns = cars_df.columns.str.lower().str.replace(' ', '_')
display(cars_df.head())

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [3]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8999 entries, 0 to 8998
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               8999 non-null   object
 1   model              8999 non-null   object
 2   year               8999 non-null   int64
 3   engine_fuel_type   8999 non-null   object
 4   engine_hp          8935 non-null   float64
 5   engine_cylinders   8969 non-null   float64
 6   transmission_type  8999 non-null   object
 7   driven_wheels      8999 non-null   object
 8   number_of_doors    8993 non-null   float64
 9   market_category    6301 non-null   object
 10  vehicle_size       8999 non-null   object
 11  vehicle_style      8999 non-null   object
 12  highway_mpg        8999 non-null   int64
 13  city_mpg           8999 non-null   int64
 14  popularity         8999 non-null   int64
 15  msrp               8999 non-null   int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.1+ MB

In [4]:
cars_df["market_category"].unique()

array(['Factory Tuner,Luxury,High-Performance', 'Luxury,Performance',
       'Luxury,High-Performance', 'Luxury', 'Performance', 'Flex Fuel',
       'Flex Fuel,Performance', nan, 'Hatchback',
       'Hatchback,Luxury,Performance', 'Hatchback,Luxury',
       'Luxury,High-Performance,Hybrid', 'Diesel,Luxury',
       'Hatchback,Performance', 'Hatchback,Factory Tuner,Performance',
       'High-Performance', 'Factory Tuner,High-Performance',
       'Exotic,High-Performance', 'Exotic,Factory Tuner,High-Performance',
       'Factory Tuner,Performance', 'Crossover', 'Exotic,Luxury',
       'Exotic,Luxury,High-Performance', 'Exotic,Luxury,Performance',
       'Factory Tuner,Luxury,Performance', 'Flex Fuel,Luxury',
       'Crossover,Luxury', 'Hatchback,Factory Tuner,Luxury,Performance',
       'Crossover,Hatchback', 'Hybrid', 'Luxury,Performance,Hybrid',
       'Crossover,Luxury,Performance,Hybrid',
       'Crossover,Luxury,Performance',
       'Exotic,Factory Tuner,Luxury,High-Performance',
       'Flex Fuel,Luxury,High-Performance', 'Crossover,Flex Fuel',
       'Diesel', 'Hatchback,Diesel', 'Crossover,Luxury,Diesel',
       'Crossover,Luxury,High-Performance',
       'Exotic,Flex Fuel,Factory Tuner,Luxury,High-Performance',
       'Exotic,Flex Fuel,Luxury,High-Performance',
       'Exotic,Factory Tuner,Luxury,Performance', 'Hatchback,Hybrid',
       'Crossover,Hybrid', 'Hatchback,Luxury,Hybrid',
       'Flex Fuel,Luxury,Performance', 'Crossover,Performance',
       'Luxury,Hybrid', 'Crossover,Flex Fuel,Luxury,Performance',
       'Crossover,Flex Fuel,Luxury', 'Crossover,Flex Fuel,Performance',
       'Hatchback,Factory Tuner,High-Performance', 'Hatchback,Flex Fuel',
       'Factory Tuner,Luxury',
       'Crossover,Factory Tuner,Luxury,High-Performance',
       'Crossover,Factory Tuner,Luxury,Performance',
       'Crossover,Hatchback,Factory Tuner,Performance',
       'Crossover,Hatchback,Performance', 'Flex Fuel,Hybrid',
       'Flex Fuel,Performance,Hybrid',
       'Crossover,Exotic,Luxury,High-Performance',
       'Crossover,Exotic,Luxury,Performance', 'Exotic,Performance',
       'Exotic,Luxury,High-Performance,Hybrid', 'Crossover,Luxury,Hybrid',
       'Flex Fuel,Factory Tuner,Luxury,High-Performance',
       'Performance,Hybrid'], dtype=object)

In [5]:
cars_df["market_category"] = cars_df["market_category"].fillna("unknown")
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8999 entries, 0 to 8998
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               8999 non-null   object
 1   model              8999 non-null   object
 2   year               8999 non-null   int64
 3   engine_fuel_type   8999 non-null   object
 4   engine_hp          8935 non-null   float64
 5   engine_cylinders   8969 non-null   float64
 6   transmission_type  8999 non-null   object
 7   driven_wheels      8999 non-null   object
 8   number_of_doors    8993 non-null   float64
 9   market_category    8999 non-null   object
 10  vehicle_size       8999 non-null   object
 11  vehicle_style      8999 non-null   object
 12  highway_mpg        8999 non-null   int64
 13  city_mpg           8999 non-null   int64
 14  popularity         8999 non-null   int64
 15  msrp               8999 non-null   int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.1+ MB

In [6]:
cars_df.fillna({"engine_hp": cars_df["engine_hp"].median()}, inplace=True)
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8999 entries, 0 to 8998
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               8999 non-null   object
 1   model              8999 non-null   object
 2   year               8999 non-null   int64
 3   engine_fuel_type   8999 non-null   object
 4   engine_hp          8999 non-null   float64
 5   engine_cylinders   8969 non-null   float64
 6   transmission_type  8999 non-null   object
 7   driven_wheels      8999 non-null   object
 8   number_of_doors    8993 non-null   float64
 9   market_category    8999 non-null   object
 10  vehicle_size       8999 non-null   object
 11  vehicle_style      8999 non-null   object
 12  highway_mpg        8999 non-null   int64
 13  city_mpg           8999 non-null   int64
 14  popularity         8999 non-null   int64
 15  msrp               8999 non-null   int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.1+ MB

In [7]:
cars_df.loc[(cars_df["engine_cylinders"].isna()) & (cars_df["engine_fuel_type"]=="electric"), ["engine_cylinders"]] = 0
cars_df.fillna({"engine_cylinders": cars_df["engine_cylinders"].median()}, inplace=True)
cars_df.dropna(subset=["number_of_doors"], inplace=True)
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8993 entries, 0 to 8998
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               8993 non-null   object
 1   model              8993 non-null   object
 2   year               8993 non-null   int64
 3   engine_fuel_type   8993 non-null   object
 4   engine_hp          8993 non-null   float64
 5   engine_cylinders   8993 non-null   float64
 6   transmission_type  8993 non-null   object
 7   driven_wheels      8993 non-null   object
 8   number_of_doors    8993 non-null   float64
 9   market_category    8993 non-null   object
 10  vehicle_size       8993 non-null   object
 11  vehicle_style      8993 non-null   object
 12  highway_mpg        8993 non-null   int64
 13  city_mpg           8993 non-null   int64
 14  popularity         8993 non-null   int64
 15  msrp               8993 non-null   int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.2+ MB

In [8]:
cars_df.duplicated(keep= "first").sum()

np.int64(573)

In [9]:
cars_df.drop_duplicates(keep= "first", inplace=True)
cars_df.info()
cars_df.duplicated(keep= "first").sum()

<class 'pandas.core.frame.DataFrame'>
Index: 8420 entries, 0 to 8998
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               8420 non-null   object
 1   model              8420 non-null   object
 2   year               8420 non-null   int64
 3   engine_fuel_type   8420 non-null   object
 4   engine_hp          8420 non-null   float64
 5   engine_cylinders   8420 non-null   float64
 6   transmission_type  8420 non-null   object
 7   driven_wheels      8420 non-null   object
 8   number_of_doors    8420 non-null   float64
 9   market_category    8420 non-null   object
 10  vehicle_size       8420 non-null   object
 11  vehicle_style      8420 non-null   object
 12  highway_mpg        8420 non-null   int64
 13  city_mpg           8420 non-null   int64
 14  popularity         8420 non-null   int64
 15  msrp               8420 non-null   int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.1+ MB

np.int64(0)

In [10]:
cars_df = cars_df.astype({
    "make": "category",
    "model": "category",
    "year": "int64",
    "engine_fuel_type": "category",
    "engine_hp": "int64",
    "engine_cylinders": "int64",
    "transmission_type": "category",
    "driven_wheels": "category",
    "number_of_doors": "int64",
    "market_category": "category",
    "vehicle_size": "category",
    "vehicle_style": "category",
    "highway_mpg": "int64",
    "city_mpg": "int64",
    "popularity": "int64",
    "msrp": "int64",
})
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8420 entries, 0 to 8998
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   make               8420 non-null   category
 1   model              8420 non-null   category
 2   year               8420 non-null   int64
 3   engine_fuel_type   8420 non-null   category
 4   engine_hp          8420 non-null   int64
 5   engine_cylinders   8420 non-null   int64
 6   transmission_type  8420 non-null   category
 7   driven_wheels      8420 non-null   category
 8   number_of_doors    8420 non-null   int64
 9   market_category    8420 non-null   category
 10  vehicle_size       8420 non-null   category
 11  vehicle_style      8420 non-null   category
 12  highway_mpg        8420 non-null   int64
 13  city_mpg           8420 non-null   int64
 14  popularity         8420 non-null   int64
 15  msrp               8420 non-null   int64
dtypes: category(8), int64(8)
memory usage: 693.4 KB

In [11]:
cars_df.to_csv("data/processed_cars_data_set.csv", sep=",", index=False)

In [12]:
cars_df["price_per_hp"] = cars_df["msrp"] / cars_df["engine_hp"]
display(cars_df.head())

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,price_per_hp
0,BMW,1 Series M,2011,premium unleaded (required),335,6,MANUAL,rear wheel drive,2,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135,137.716418
1,BMW,1 Series,2011,premium unleaded (required),300,6,MANUAL,rear wheel drive,2,"Luxury,Performance",Compact,Convertible,28,19,3916,40650,135.500000
2,BMW,1 Series,2011,premium unleaded (required),300,6,MANUAL,rear wheel drive,2,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350,121.166667
3,BMW,1 Series,2011,premium unleaded (required),230,6,MANUAL,rear wheel drive,2,"Luxury,Performance",Compact,Coupe,28,18,3916,29450,128.043478
4,BMW,1 Series,2011,premium unleaded (required),230,6,MANUAL,rear wheel drive,2,Luxury,Compact,Convertible,28,18,3916,34500,150.000000

In [13]:
bmw_cars = cars_df[cars_df["make"] == "BMW"]
top5_bmw = bmw_cars.nlargest(5, "msrp")
display(top5_bmw)

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp,price_per_hp
720,BMW,7 Series,2015,premium unleaded (required),535,12,AUTOMATIC,rear wheel drive,4,"Luxury,High-Performance",Large,Sedan,20,13,3916,141200,263.925234
1397,BMW,ALPINA B7,2017,premium unleaded (required),600,8,AUTOMATIC,all wheel drive,4,"Factory Tuner,Luxury,High-Performance",Large,Sedan,24,16,3916,137000,228.333333
1398,BMW,Alpina,2003,premium unleaded (required),375,8,AUTOMATIC,rear wheel drive,2,"Exotic,Factory Tuner,Luxury,High-Performance",Compact,Convertible,19,13,3916,136900,365.066667
1389,BMW,ALPINA B7,2014,premium unleaded (required),540,8,AUTOMATIC,all wheel drive,4,"Factory Tuner,Luxury,High-Performance",Large,Sedan,24,16,3916,135200,250.370370
1395,BMW,ALPINA B7,2015,premium unleaded (required),540,8,AUTOMATIC,all wheel drive,4,"Factory Tuner,Luxury,High-Performance",Large,Sedan,24,16,3916,135200,250.370370

In [14]:
audi_cars = cars_df[cars_df["make"] == "Audi"]
audi_cars["transmission_type"].value_counts()

transmission_type
AUTOMATIC           131
AUTOMATED_MANUAL    111
MANUAL               58
DIRECT_DRIVE          0
UNKNOWN               0
Name: count, dtype: int64

In [15]:
cars_df["vehicle_style"].value_counts()

vehicle_style
Sedan                  2477
4dr SUV                1692
Coupe                  1024
Convertible             606
4dr Hatchback           528
Wagon                   422
Crew Cab Pickup         368
2dr Hatchback           329
Extended Cab Pickup     327
Regular Cab Pickup      214
Passenger Minivan       188
2dr SUV                  83
Cargo Van                63
Passenger Van            52
Cargo Minivan            37
Convertible SUV          10
Name: count, dtype: int64

In [16]:
cars_df.to_csv("data/processed_cars_data_set.csv", sep=",", index=False)