In [11]:
import pandas as pd

apartments_df = pd.read_csv("data/appartments_data_set.csv")
display(apartments_df.head(10))

,Unnamed: 0,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,is_apartment,studio,kitchen_area,balcony,locality_name,days_exposition
0,0,7312500.0,108.00,2024-05-15,3,2.70,16.0,51.00,8,NaN,False,25.00,NaN,Kyiv,NaN
1,1,1884375.0,40.40,2024-08-14,1,NaN,11.0,18.60,1,NaN,False,11.00,2.0,Brovary,81.0
2,2,2922750.0,56.00,2023-11-06,2,NaN,5.0,34.30,4,NaN,False,8.30,0.0,Kyiv,558.0
3,3,36506250.0,159.00,2024-03-19,3,NaN,14.0,NaN,9,NaN,False,NaN,0.0,Kyiv,424.0
4,4,5625000.0,100.00,2024-06-12,2,3.03,14.0,32.00,13,NaN,False,41.00,NaN,Kyiv,121.0
5,5,1625625.0,30.40,2024-10-08,1,NaN,12.0,14.40,5,NaN,False,9.10,NaN,Boyarka,55.0
6,6,2081250.0,37.30,2024-03-24,1,NaN,26.0,10.60,6,NaN,False,14.40,1.0,Hostomel,155.0
7,7,4452188.0,71.60,2024-11-16,2,NaN,24.0,NaN,22,NaN,False,18.90,2.0,Kyiv,NaN
8,8,1631250.0,33.16,2024-03-09,1,NaN,27.0,15.43,26,NaN,False,8.81,NaN,Bucha,189.0
9,9,3037500.0,61.00,2024-03-10,3,2.50,9.0,43.60,7,NaN,False,6.50,2.0,Kyiv,289.0

In [12]:
apartments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23699 entries, 0 to 23698
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            23699 non-null  int64
 1   last_price            23699 non-null  float64
 2   total_area            23699 non-null  float64
 3   first_day_exposition  23699 non-null  object
 4   rooms                 23699 non-null  int64
 5   ceiling_height        14504 non-null  float64
 6   floors_total          23613 non-null  float64
 7   living_area           21796 non-null  float64
 8   floor                 23699 non-null  int64
 9   is_apartment          2775 non-null   object
 10  studio                23699 non-null  bool
 11  kitchen_area          21421 non-null  float64
 12  balcony               12180 non-null  float64
 13  locality_name         23699 non-null  object
 14  days_exposition       20518 non-null  float64
dtypes: bool(1), float64(8), int64(3), object(3)
memory usage: 2.6+ MB

In [13]:
apartments_df.drop(columns=["Unnamed: 0"], inplace=True)
apartments_df.fillna({"ceiling_height": apartments_df["ceiling_height"].median()}, inplace=True)
apartments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23699 entries, 0 to 23698
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   last_price            23699 non-null  float64
 1   total_area            23699 non-null  float64
 2   first_day_exposition  23699 non-null  object
 3   rooms                 23699 non-null  int64
 4   ceiling_height        23699 non-null  float64
 5   floors_total          23613 non-null  float64
 6   living_area           21796 non-null  float64
 7   floor                 23699 non-null  int64
 8   is_apartment          2775 non-null   object
 9   studio                23699 non-null  bool
 10  kitchen_area          21421 non-null  float64
 11  balcony               12180 non-null  float64
 12  locality_name         23699 non-null  object
 13  days_exposition       20518 non-null  float64
dtypes: bool(1), float64(8), int64(2), object(3)
memory usage: 2.4+ MB

In [14]:
apartments_df.dropna(subset=["floors_total"], inplace=True)
apartments_df.drop(columns=["is_apartment"], inplace=True)
apartments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23613 entries, 0 to 23698
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   last_price            23613 non-null  float64
 1   total_area            23613 non-null  float64
 2   first_day_exposition  23613 non-null  object
 3   rooms                 23613 non-null  int64
 4   ceiling_height        23613 non-null  float64
 5   floors_total          23613 non-null  float64
 6   living_area           21743 non-null  float64
 7   floor                 23613 non-null  int64
 8   studio                23613 non-null  bool
 9   kitchen_area          21382 non-null  float64
 10  balcony               12133 non-null  float64
 11  locality_name         23613 non-null  object
 12  days_exposition       20441 non-null  float64
dtypes: bool(1), float64(8), int64(2), object(2)
memory usage: 2.4+ MB

In [15]:
ratio = (apartments_df["living_area"] / apartments_df["total_area"]).median()
apartments_df["living_area"] = apartments_df["living_area"].fillna(apartments_df["total_area"] * ratio)
print("ratio = ", ratio)
apartments_df.info()

ratio =  0.5681818181818182
<class 'pandas.core.frame.DataFrame'>
Index: 23613 entries, 0 to 23698
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   last_price            23613 non-null  float64
 1   total_area            23613 non-null  float64
 2   first_day_exposition  23613 non-null  object
 3   rooms                 23613 non-null  int64
 4   ceiling_height        23613 non-null  float64
 5   floors_total          23613 non-null  float64
 6   living_area           23613 non-null  float64
 7   floor                 23613 non-null  int64
 8   studio                23613 non-null  bool
 9   kitchen_area          21382 non-null  float64
 10  balcony               12133 non-null  float64
 11  locality_name         23613 non-null  object
 12  days_exposition       20441 non-null  float64
dtypes: bool(1), float64(8), int64(2), object(2)
memory usage: 2.4+ MB

In [16]:
apartments_df.fillna({
    "kitchen_area": apartments_df["kitchen_area"].median(),
    "balcony": 0
}, inplace=True)
apartments_df.drop(columns=["days_exposition"], inplace=True)
apartments_df.info()
display(apartments_df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 23613 entries, 0 to 23698
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   last_price            23613 non-null  float64
 1   total_area            23613 non-null  float64
 2   first_day_exposition  23613 non-null  object
 3   rooms                 23613 non-null  int64
 4   ceiling_height        23613 non-null  float64
 5   floors_total          23613 non-null  float64
 6   living_area           23613 non-null  float64
 7   floor                 23613 non-null  int64
 8   studio                23613 non-null  bool
 9   kitchen_area          23613 non-null  float64
 10  balcony               23613 non-null  float64
 11  locality_name         23613 non-null  object
dtypes: bool(1), float64(7), int64(2), object(2)
memory usage: 2.2+ MB

,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,studio,kitchen_area,balcony,locality_name
0,7312500.0,108.0,2024-05-15,3,2.70,16.0,51.000000,8,False,25.0,0.0,Kyiv
1,1884375.0,40.4,2024-08-14,1,2.65,11.0,18.600000,1,False,11.0,2.0,Brovary
2,2922750.0,56.0,2023-11-06,2,2.65,5.0,34.300000,4,False,8.3,0.0,Kyiv
3,36506250.0,159.0,2024-03-19,3,2.65,14.0,90.340909,9,False,9.1,0.0,Kyiv
4,5625000.0,100.0,2024-06-12,2,3.03,14.0,32.000000,13,False,41.0,0.0,Kyiv

In [17]:
apartments_df["first_day_exposition"] = pd.to_datetime(apartments_df["first_day_exposition"])
apartments_df = apartments_df.astype({
    "last_price": "int64",
    "floors_total": "int64",
    "balcony": "int64",
    "locality_name": "category",
})
apartments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23613 entries, 0 to 23698
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   last_price            23613 non-null  int64
 1   total_area            23613 non-null  float64
 2   first_day_exposition  23613 non-null  datetime64[ns]
 3   rooms                 23613 non-null  int64
 4   ceiling_height        23613 non-null  float64
 5   floors_total          23613 non-null  int64
 6   living_area           23613 non-null  float64
 7   floor                 23613 non-null  int64
 8   studio                23613 non-null  bool
 9   kitchen_area          23613 non-null  float64
 10  balcony               23613 non-null  int64
 11  locality_name         23613 non-null  category
dtypes: bool(1), category(1), datetime64[ns](1), float64(4), int64(5)
memory usage: 2.0 MB

In [18]:
apartments_df.duplicated(keep="first").sum()

np.int64(0)

In [19]:
apartments_df["price_per_sqm"] = apartments_df["last_price"] / apartments_df["total_area"]
display(apartments_df.head())

,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,studio,kitchen_area,balcony,locality_name,price_per_sqm
0,7312500,108.0,2024-05-15,3,2.70,16,51.000000,8,False,25.0,0,Kyiv,67708.333333
1,1884375,40.4,2024-08-14,1,2.65,11,18.600000,1,False,11.0,2,Brovary,46642.945545
2,2922750,56.0,2023-11-06,2,2.65,5,34.300000,4,False,8.3,0,Kyiv,52191.964286
3,36506250,159.0,2024-03-19,3,2.65,14,90.340909,9,False,9.1,0,Kyiv,229599.056604
4,5625000,100.0,2024-06-12,2,3.03,14,32.000000,13,False,41.0,0,Kyiv,56250.000000

In [20]:
import data_profiling

profiler = data_profiling.ProfileReport(apartments_df)
profiler.to_file("data/apartments_report.html")

C:\Users\romab\Desktop\data_analysis\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Summarize dataset:  39%|███▉      | 7/18 [00:00<00:00, 32.18it/s, Describe variable: price_per_sqm]
100%|██████████| 13/13 [00:00<00:00, 1263.81it/s]
Summarize dataset: 100%|██████████| 122/122 [00:07<00:00, 16.79it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.90s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.96it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 74.29it/s]

In [21]:
apartments_df["locality_name"].unique()

['Kyiv', 'Brovary', 'Boyarka', 'Hostomel', 'Bucha', 'Boryspil', 'Irpin', 'Vyshneve', 'Borshchahivka']
Categories (9, object): ['Borshchahivka', 'Boryspil', 'Boyarka', 'Brovary', ..., 'Hostomel', 'Irpin', 'Kyiv', 'Vyshneve']

In [22]:
kiev_apart = apartments_df[apartments_df["locality_name"] == "Kyiv"]
kiev_apart["rooms"].value_counts()

rooms
2     5082
1     4912
3     4107
4      966
5      290
0      109
6       98
7       57
8       11
9        8
10       3
11       2
14       2
15       1
19       1
16       1
12       1
Name: count, dtype: int64

In [23]:
irpin_apart = apartments_df[(apartments_df["locality_name"] == "Irpin") & (apartments_df["rooms"] == 1)]
irpin_avg_price = irpin_apart["last_price"].mean()
print(irpin_avg_price)

1596620.5195530725

In [24]:
studio_count = apartments_df["studio"].sum()
total_count = apartments_df.shape[0]
studio_share = studio_count / total_count * 100

print("Количество студий:", studio_count)
print("Всего квартир:", total_count)
print(f"Доля студий: {studio_share:.2f}%")

Количество студий: 146
Всего квартир: 23613
Доля студий: 0.62%

In [25]:
kiev_apart = apartments_df[apartments_df["locality_name"] == "Kyiv"]

print("mean:", kiev_apart["price_per_sqm"].mean())
print("median:", kiev_apart["price_per_sqm"].median())
print("std:", kiev_apart["price_per_sqm"].std())
print("min:", kiev_apart["price_per_sqm"].min())
print("max:", kiev_apart["price_per_sqm"].max())

mean: 64613.74369412168
median: 58935.67639257294
std: 29619.074597246523
min: 62.89908256880734
max: 1072968.75

In [26]:
apartments_df.to_csv("data/processed_apartments_data_set.csv", index=False)