In [1]:
import pandas as pd

customers_df = pd.read_csv("data/customers.csv")
orders_part_1_df = pd.read_csv("data/orders_part_1.csv")
orders_part_2_df = pd.read_csv("data/orders_part_2.csv")
display(customers_df.head(10))
display(orders_part_1_df.head(10))
display(orders_part_2_df.head(10))

,CustomerID,Genre,Age,Annual_Income,Spending_Score,Location
0,002c2626-e984-459b-b96e-f66b9bf1c8d4,Male,19,1500,39,Kyiv
1,0145193c-cf85-436e-92cc-17cb5b0d04eb,Male,21,1500,81,Brovary
2,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,Female,20,1600,6,Kyiv
3,03020226-ebdd-49c3-a545-1d2c01a91620,Female,23,1600,77,Boryspil
4,037f2615-2d98-4d9d-ba88-1aa37263dc0e,Female,31,1700,40,Kyiv
5,0391f9c8-ce5d-43f2-88cd-bf4b8a6673a4,Female,22,1700,76,Boyarka
6,045e6cd9-0bd9-4b88-808b-10c5a4a13d0d,Female,35,1800,6,Hostomel
7,04e44f80-9f4e-4fc9-a45c-a81097d07a02,Female,23,1800,94,Kyiv
8,0602013d-f63b-4a5a-b212-19a5562ad344,Male,64,1900,3,Bucha
9,07065bc8-5d9c-4177-82f9-f5e9b64444f1,Female,30,1900,72,Kyiv

,InvoiceNo,CustomerID,Description,Quantity,UnitPrice,Category,Discount,PaymentMethod
0,INV100290,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,USB-C Cable,8.0,65.59,Accessories,0.22,Credit Card
1,INV100278,0d88c95d-0f2f-4e4b-98c4-427c91125f7d,Gaming Keyboard,2.0,14.44,Gaming,0.07,paypal
2,INV100561,09c9ad28-738f-4e6c-b61b-6eda53404915,Gaming Keyboard,10.0,19.09,Gaming,0.24,PayPal
3,INV100542,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,Power Bank,6.0,6.27,Accessories,0.06,Credit Card
4,INV100787,08508316-a3be-4bcd-b6b7-91145174a8ba,Power Bank,2.0,67.56,Accessories,0.15,credit card
5,INV100899,04e44f80-9f4e-4fc9-a45c-a81097d07a02,Laptop Stand,10.0,17.90,Office,0.25,PayPal
6,INV100475,03020226-ebdd-49c3-a545-1d2c01a91620,Laptop Stand,7.0,8.11,Office,0.10,PayPal
7,INV100724,10bf93a6-29de-4f41-afd0-e62610ac2068,Bluetooth Speaker,6.0,10.95,Electronics,0.16,Bank Transfer
8,INV100144,0a0ad13a-2fac-484f-b54c-9607340f0524,Wireless Mouse,7.0,54.45,Electronics,0.05,Bank Transfer
9,INV100766,045e6cd9-0bd9-4b88-808b-10c5a4a13d0d,Gaming Keyboard,1.0,56.38,Gaming,0.25,PayPal

,InvoiceNo,CustomerID,Description,Quantity,UnitPrice,Category,Discount,PaymentMethod
0,INV100866,10bf93a6-29de-4f41-afd0-e62610ac2068,LED Monitor,7.0,42.62,Electronics,0.01,credit card
1,INV100678,0f4490c6-673c-4a29-a1fa-59dfebeb7714,Gaming Keyboard,7.0,33.80,Gaming,0.05,PayPal
2,INV100877,0a0ad13a-2fac-484f-b54c-9607340f0524,Laptop Stand,6.0,48.46,Office,0.21,credit card
3,INV100640,002c2626-e984-459b-b96e-f66b9bf1c8d4,Wireless Mouse,8.0,64.26,Electronics,0.07,paypal
4,INV100832,0a0ad13a-2fac-484f-b54c-9607340f0524,USB-C Cable,6.0,40.50,Accessories,0.04,Bank Transfer
5,INV100620,0145193c-cf85-436e-92cc-17cb5b0d04eb,Wireless Mouse,4.0,21.20,Electronics,0.04,Credit Card
6,INV100554,07a005e9-45b1-446b-a374-c8490f7c5dfa,Power Bank,8.0,49.37,Accessories,0.24,Credit Card
7,INV100843,10bf93a6-29de-4f41-afd0-e62610ac2068,Wireless Mouse,2.0,37.69,Electronics,0.12,Bank Transfer
8,INV100616,10bf93a6-29de-4f41-afd0-e62610ac2068,Laptop Stand,4.0,73.08,Office,0.10,Bank Transfer
9,INV100241,0602013d-f63b-4a5a-b212-19a5562ad344,Laptop Stand,10.0,32.80,Office,0.06,PayPal

In [2]:
orders = pd.concat([orders_part_1_df, orders_part_2_df], axis=0, ignore_index=True)
orders

,InvoiceNo,CustomerID,Description,Quantity,UnitPrice,Category,Discount,PaymentMethod
0,INV100290,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,USB-C Cable,8.0,65.59,Accessories,0.22,Credit Card
1,INV100278,0d88c95d-0f2f-4e4b-98c4-427c91125f7d,Gaming Keyboard,2.0,14.44,Gaming,0.07,paypal
2,INV100561,09c9ad28-738f-4e6c-b61b-6eda53404915,Gaming Keyboard,10.0,19.09,Gaming,0.24,PayPal
3,INV100542,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,Power Bank,6.0,6.27,Accessories,0.06,Credit Card
4,INV100787,08508316-a3be-4bcd-b6b7-91145174a8ba,Power Bank,2.0,67.56,Accessories,0.15,credit card
...,...,...,...,...,...,...,...,...
95,INV100830,0d88c95d-0f2f-4e4b-98c4-427c91125f7d,Gaming Keyboard,3.0,15.09,Gaming,0.26,Credit Card
96,INV100204,0f4490c6-673c-4a29-a1fa-59dfebeb7714,Power Bank,8.0,69.47,Accessories,0.10,PayPal
97,INV100740,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,Bluetooth Speaker,9.0,15.25,Electronics,0.08,credit card
98,INV100295,09c9ad28-738f-4e6c-b61b-6eda53404915,Laptop Stand,3.0,74.67,Office,0.17,Credit Card
99,INV100258,0602013d-f63b-4a5a-b212-19a5562ad344,HDMI Adapter,7.0,75.11,Accessories,0.29,paypal

In [3]:
orders.duplicated().sum()

np.int64(0)

In [4]:
full_df = orders.merge(customers_df, how="left", on="CustomerID")
full_df

,InvoiceNo,CustomerID,Description,Quantity,UnitPrice,Category,Discount,PaymentMethod,Genre,Age,Annual_Income,Spending_Score,Location
0,INV100290,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,USB-C Cable,8.0,65.59,Accessories,0.22,Credit Card,Female,20,1600,6,Kyiv
1,INV100278,0d88c95d-0f2f-4e4b-98c4-427c91125f7d,Gaming Keyboard,2.0,14.44,Gaming,0.07,paypal,Male,52,2300,29,Boryspil
2,INV100561,09c9ad28-738f-4e6c-b61b-6eda53404915,Gaming Keyboard,10.0,19.09,Gaming,0.24,PayPal,Male,22,2000,79,Kyiv
3,INV100542,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,Power Bank,6.0,6.27,Accessories,0.06,Credit Card,Female,20,1600,6,Kyiv
4,INV100787,08508316-a3be-4bcd-b6b7-91145174a8ba,Power Bank,2.0,67.56,Accessories,0.15,credit card,Female,58,2000,15,Irpin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,INV100830,0d88c95d-0f2f-4e4b-98c4-427c91125f7d,Gaming Keyboard,3.0,15.09,Gaming,0.26,Credit Card,Male,52,2300,29,Boryspil
96,INV100204,0f4490c6-673c-4a29-a1fa-59dfebeb7714,Power Bank,8.0,69.47,Accessories,0.10,PayPal,Male,35,2400,35,Hostomel
97,INV100740,01eac1fb-42ac-4ad4-afd6-fe01d3e2dcf5,Bluetooth Speaker,9.0,15.25,Electronics,0.08,credit card,Female,20,1600,6,Kyiv
98,INV100295,09c9ad28-738f-4e6c-b61b-6eda53404915,Laptop Stand,3.0,74.67,Office,0.17,Credit Card,Male,22,2000,79,Kyiv
99,INV100258,0602013d-f63b-4a5a-b212-19a5562ad344,HDMI Adapter,7.0,75.11,Accessories,0.29,paypal,Male,64,1900,3,Bucha

In [5]:
task1 = full_df.groupby(["Location", "Category"]).size().reset_index(name="OrderCount")
task1

    Location     Category  OrderCount
0   Boryspil  Accessories           5
1   Boryspil  Electronics          10
2   Boryspil       Gaming           2
3   Boryspil       Office           5
4    Boyarka  Accessories           1
5    Boyarka  Electronics           3
6    Brovary  Accessories           1
7    Brovary  Electronics           2
8    Brovary       Office           1
9      Bucha  Accessories           3
10     Bucha       Office           1
11  Hostomel  Accessories           5
12  Hostomel  Electronics           3
13  Hostomel       Gaming           2
14  Hostomel       Office           4
15     Irpin  Accessories           3
16     Irpin  Electronics           1
17     Irpin       Office           1
18      Kyiv  Accessories          18
19      Kyiv  Electronics          13
20      Kyiv       Gaming           5
21      Kyiv       Office           7
22  Vyshneve  Accessories           1
23  Vyshneve  Electronics           3

In [6]:
keyboards = full_df[full_df["Description"] == "Gaming Keyboard"]
task2 = keyboards.groupby("Location").size().sort_values(ascending=False)
task2

Location
Kyiv        5
Boryspil    2
Hostomel    2
dtype: int64

In [7]:
rich_customers = full_df[full_df["Annual_Income"] > 2000]
task3 = rich_customers.groupby("Category").size().sort_values(ascending=False)
task3

Category
Accessories    11
Electronics    11
Office          6
Gaming          4
dtype: int64